services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cpp_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: stephtanner1/cpp-backend
    environment:
      DB_HOST: postgres
      DB_NAME: cpp_database
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-securepassword123}
      DB_PORT: 5432
    ports:
      - "5000:5000" # Change if port 5000 is already in use
    # Optional: Mount SQLite data if migrating from a previous sqlite version
    # volumes:
    #  - backend_data:/app/data 
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: stephtanner1/cpp-frontend
    # If using a custom backend port, uncomment and update:
    # environment:
    #   - VITE_BACKEND_URL=http://[serverip/hostname]:[port]
    # Example: VITE_BACKEND_URL=http://192.168.0.111:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  # backend_data: # Uncomment if migrating from SQLite
