services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cpp_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: stephtanner1/cpp-backend:beta
    environment:
      DB_HOST: postgres
      DB_NAME: cpp_database
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: stephtanner1/cpp-frontend:beta
    environment:
      - VITE_API_URL=http://backend:5000
    ports:
      - 3333:3000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: null

networks: {}
