version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: centsperpoint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    image: stephtanner1/cpp-backend:latest
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
    # Optional: Mount SQLite data if migrating from a previous sqlite version
    # volumes:
    #  - backend_data:/app/data 
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: stephtanner1/cpp-frontend:latest
    # Uncomment VITE_API_URL only if you change the backend port above
    # Replace YOUR_SERVER_IP with localhost (local) or your server's IP (remote)
    # Example: VITE_API_URL=http://192.168.0.100:8080
    # environment:
    #   - VITE_API_URL=http://YOUR_SERVER_IP:BACKEND_PORT
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
# backend_data: -- optional, uncomment if migrating from a previous sqlite version
