version: '3.8'
services:
  backend:
    image: stephtanner1/cpp-backend:beta
    ports:
      - 5000:5000
    volumes:
      - backend_data:/app/data
  frontend:
    image: stephtanner1/cpp-frontend:beta
    ports:
      - 3300:3000
    depends_on:
      - backend

volumes:
  backend_data: null 